//! Migration department: `Migration/DepartmentName` — flags `# rubocop:
//! disable`/`# rubocop:todo`/`# rubocop:enable` directive comments whose cop
//! names lack a department prefix (`# rubocop:disable Alias` instead of
//! `# rubocop:disable Style/Alias`), autocorrecting by qualifying the name
//! against rubocop's built-in cop registry — falling back to its legacy-name
//! obsoletion table for cops since renamed/moved. Ported from rubocop's
//! `RuboCop::Cop::Migration::DepartmentName`.
use super::Cops;
use std::sync::OnceLock;

/// The 9 rubocop-core departments (`RuboCop::Cop::Registry.global.
/// departments` for a bare `require 'rubocop'` — no extension gems loaded,
/// matching this engine's scope). A bare department name in a disable
/// comment (`# rubocop:disable Style`) is valid content, not a
/// department-less COP name.
const DEPARTMENTS: &[&str] =
    &["Bundler", "Gemspec", "Layout", "Lint", "Metrics", "Migration", "Naming", "Security", "Style"];

/// short cop name -> its (unique) department, generated from rubocop
/// 1.88.0's `RuboCop::Cop::Registry.global.to_h.keys` (core cops only, no
/// extension gems — this engine's scope). Two short names are genuinely
/// ambiguous across departments in real rubocop (`MultipleComparison`,
/// `SelfAssignment` — both `Lint` and `Style`) and are deliberately omitted
/// here: real `Registry#qualify_badge` finds two candidate departments for
/// those and `Registry#qualified_cop_name` raises `AmbiguousCopName` (a
/// `warn: false` call doesn't suppress that raise) — not reachable from any
/// well-formed disable comment this fixture exercises, and reproducing
/// upstream's crash isn't worth doing on purpose.
const COP_DEPARTMENTS: &[(&str, &str)] = &[
    ("AbcSize", "Metrics"),
    ("AccessModifierDeclarations", "Style"),
    ("AccessModifierIndentation", "Layout"),
    ("AccessorGrouping", "Style"),
    ("AccessorMethodName", "Naming"),
    ("AddRuntimeDependency", "Gemspec"),
    ("Alias", "Style"),
    ("AmbiguousAssignment", "Lint"),
    ("AmbiguousBlockAssociation", "Lint"),
    ("AmbiguousEndlessMethodDefinition", "Style"),
    ("AmbiguousOperator", "Lint"),
    ("AmbiguousOperatorPrecedence", "Lint"),
    ("AmbiguousRange", "Lint"),
    ("AmbiguousRegexpLiteral", "Lint"),
    ("AndOr", "Style"),
    ("ArgumentAlignment", "Layout"),
    ("ArgumentsForwarding", "Style"),
    ("ArrayAlignment", "Layout"),
    ("ArrayCoercion", "Style"),
    ("ArrayFirstLast", "Style"),
    ("ArrayIntersect", "Style"),
    ("ArrayIntersectWithSingleElement", "Style"),
    ("ArrayJoin", "Style"),
    ("ArrayLiteralInRegexp", "Lint"),
    ("AsciiComments", "Style"),
    ("AsciiIdentifiers", "Naming"),
    ("AssignmentInCondition", "Lint"),
    ("AssignmentIndentation", "Layout"),
    ("Attr", "Style"),
    ("AttributeAssignment", "Gemspec"),
    ("AutoResourceCleanup", "Style"),
    ("BarePercentLiterals", "Style"),
    ("BeginBlock", "Style"),
    ("BeginEndAlignment", "Layout"),
    ("BigDecimalNew", "Lint"),
    ("BinaryOperatorParameterName", "Naming"),
    ("BinaryOperatorWithIdenticalOperands", "Lint"),
    ("BisectedAttrAccessor", "Style"),
    ("BitwisePredicate", "Style"),
    ("BlockAlignment", "Layout"),
    ("BlockComments", "Style"),
    ("BlockDelimiters", "Style"),
    ("BlockEndNewline", "Layout"),
    ("BlockForwarding", "Naming"),
    ("BlockLength", "Metrics"),
    ("BlockNesting", "Metrics"),
    ("BlockParameterName", "Naming"),
    ("BooleanSymbol", "Lint"),
    ("CaseEquality", "Style"),
    ("CaseIndentation", "Layout"),
    ("CaseLikeIf", "Style"),
    ("CharacterLiteral", "Style"),
    ("CircularArgumentReference", "Lint"),
    ("ClassAndModuleCamelCase", "Naming"),
    ("ClassAndModuleChildren", "Style"),
    ("ClassCheck", "Style"),
    ("ClassEqualityComparison", "Style"),
    ("ClassLength", "Metrics"),
    ("ClassMethods", "Style"),
    ("ClassMethodsDefinitions", "Style"),
    ("ClassStructure", "Layout"),
    ("ClassVars", "Style"),
    ("ClosingHeredocIndentation", "Layout"),
    ("ClosingParenthesisIndentation", "Layout"),
    ("CollectionCompact", "Style"),
    ("CollectionLiteralLength", "Metrics"),
    ("CollectionMethods", "Style"),
    ("CollectionQuerying", "Style"),
    ("ColonMethodCall", "Style"),
    ("ColonMethodDefinition", "Style"),
    ("CombinableDefined", "Style"),
    ("CombinableLoops", "Style"),
    ("CommandLiteral", "Style"),
    ("CommentAnnotation", "Style"),
    ("CommentIndentation", "Layout"),
    ("CommentedKeyword", "Style"),
    ("ComparableBetween", "Style"),
    ("ComparableClamp", "Style"),
    ("CompoundHash", "Security"),
    ("ConcatArrayLiterals", "Style"),
    ("ConditionPosition", "Layout"),
    ("ConditionalAssignment", "Style"),
    ("ConstantDefinitionInBlock", "Lint"),
    ("ConstantName", "Naming"),
    ("ConstantOverwrittenInRescue", "Lint"),
    ("ConstantReassignment", "Lint"),
    ("ConstantResolution", "Lint"),
    ("ConstantVisibility", "Style"),
    ("CopDirectiveSyntax", "Lint"),
    ("Copyright", "Style"),
    ("CyclomaticComplexity", "Metrics"),
    ("DataDefineOverride", "Lint"),
    ("DataInheritance", "Style"),
    ("DateTime", "Style"),
    ("Debugger", "Lint"),
    ("DefEndAlignment", "Layout"),
    ("DefWithParentheses", "Style"),
    ("DepartmentName", "Migration"),
    ("DependencyVersion", "Gemspec"),
    ("DeprecatedAttributeAssignment", "Gemspec"),
    ("DeprecatedClassMethods", "Lint"),
    ("DeprecatedConstants", "Lint"),
    ("DeprecatedOpenSSLConstant", "Lint"),
    ("DevelopmentDependencies", "Gemspec"),
    ("DigChain", "Style"),
    ("Dir", "Style"),
    ("DirEmpty", "Style"),
    ("DisableCopsWithinSourceCodeDirective", "Style"),
    ("DisjunctiveAssignmentInConstructor", "Lint"),
    ("DocumentDynamicEvalDefinition", "Style"),
    ("Documentation", "Style"),
    ("DocumentationMethod", "Style"),
    ("DotPosition", "Layout"),
    ("DoubleCopDisableDirective", "Style"),
    ("DoubleNegation", "Style"),
    ("DuplicateBranch", "Lint"),
    ("DuplicateCaseCondition", "Lint"),
    ("DuplicateElsifCondition", "Lint"),
    ("DuplicateHashKey", "Lint"),
    ("DuplicateMagicComment", "Lint"),
    ("DuplicateMatchPattern", "Lint"),
    ("DuplicateMethods", "Lint"),
    ("DuplicateRegexpCharacterClassElement", "Lint"),
    ("DuplicateRequire", "Lint"),
    ("DuplicateRescueException", "Lint"),
    ("DuplicateSetElement", "Lint"),
    ("DuplicatedAssignment", "Gemspec"),
    ("DuplicatedGem", "Bundler"),
    ("DuplicatedGroup", "Bundler"),
    ("EachForSimpleLoop", "Style"),
    ("EachWithObject", "Style"),
    ("EachWithObjectArgument", "Lint"),
    ("ElseAlignment", "Layout"),
    ("ElseLayout", "Lint"),
    ("EmptyBlock", "Lint"),
    ("EmptyBlockParameter", "Style"),
    ("EmptyCaseCondition", "Style"),
    ("EmptyClass", "Lint"),
    ("EmptyClassDefinition", "Style"),
    ("EmptyComment", "Layout"),
    ("EmptyConditionalBody", "Lint"),
    ("EmptyElse", "Style"),
    ("EmptyEnsure", "Lint"),
    ("EmptyExpression", "Lint"),
    ("EmptyFile", "Lint"),
    ("EmptyHeredoc", "Style"),
    ("EmptyInPattern", "Lint"),
    ("EmptyInterpolation", "Lint"),
    ("EmptyLambdaParameter", "Style"),
    ("EmptyLineAfterGuardClause", "Layout"),
    ("EmptyLineAfterMagicComment", "Layout"),
    ("EmptyLineAfterMultilineCondition", "Layout"),
    ("EmptyLineBetweenDefs", "Layout"),
    ("EmptyLines", "Layout"),
    ("EmptyLinesAfterModuleInclusion", "Layout"),
    ("EmptyLinesAroundAccessModifier", "Layout"),
    ("EmptyLinesAroundArguments", "Layout"),
    ("EmptyLinesAroundAttributeAccessor", "Layout"),
    ("EmptyLinesAroundBeginBody", "Layout"),
    ("EmptyLinesAroundBlockBody", "Layout"),
    ("EmptyLinesAroundClassBody", "Layout"),
    ("EmptyLinesAroundExceptionHandlingKeywords", "Layout"),
    ("EmptyLinesAroundMethodBody", "Layout"),
    ("EmptyLinesAroundModuleBody", "Layout"),
    ("EmptyLiteral", "Style"),
    ("EmptyMethod", "Style"),
    ("EmptyStringInsideInterpolation", "Style"),
    ("EmptyWhen", "Lint"),
    ("Encoding", "Style"),
    ("EndAlignment", "Layout"),
    ("EndBlock", "Style"),
    ("EndOfLine", "Layout"),
    ("EndlessMethod", "Style"),
    ("EnsureReturn", "Lint"),
    ("EnvHome", "Style"),
    ("ErbNewArguments", "Lint"),
    ("Eval", "Security"),
    ("EvalWithLocation", "Style"),
    ("EvenOdd", "Style"),
    ("ExactRegexpMatch", "Style"),
    ("ExpandPathArguments", "Style"),
    ("ExplicitBlockArgument", "Style"),
    ("ExponentialNotation", "Style"),
    ("ExtraSpacing", "Layout"),
    ("FetchEnvVar", "Style"),
    ("FileEmpty", "Style"),
    ("FileName", "Naming"),
    ("FileNull", "Style"),
    ("FileOpen", "Style"),
    ("FileRead", "Style"),
    ("FileTouch", "Style"),
    ("FileWrite", "Style"),
    ("FirstArgumentIndentation", "Layout"),
    ("FirstArrayElementIndentation", "Layout"),
    ("FirstArrayElementLineBreak", "Layout"),
    ("FirstHashElementIndentation", "Layout"),
    ("FirstHashElementLineBreak", "Layout"),
    ("FirstMethodArgumentLineBreak", "Layout"),
    ("FirstMethodParameterLineBreak", "Layout"),
    ("FirstParameterIndentation", "Layout"),
    ("FlipFlop", "Lint"),
    ("FloatComparison", "Lint"),
    ("FloatDivision", "Style"),
    ("FloatOutOfRange", "Lint"),
    ("For", "Style"),
    ("FormatParameterMismatch", "Lint"),
    ("FormatString", "Style"),
    ("FormatStringToken", "Style"),
    ("FrozenStringLiteralComment", "Style"),
    ("GemComment", "Bundler"),
    ("GemFilename", "Bundler"),
    ("GemVersion", "Bundler"),
    ("GlobalStdStream", "Style"),
    ("GlobalVars", "Style"),
    ("GuardClause", "Style"),
    ("HashAlignment", "Layout"),
    ("HashAsLastArrayItem", "Style"),
    ("HashCompareByIdentity", "Lint"),
    ("HashConversion", "Style"),
    ("HashEachMethods", "Style"),
    ("HashExcept", "Style"),
    ("HashFetchChain", "Style"),
    ("HashLikeCase", "Style"),
    ("HashLookupMethod", "Style"),
    ("HashNewWithKeywordArgumentsAsDefault", "Lint"),
    ("HashSlice", "Style"),
    ("HashSyntax", "Style"),
    ("HashTransformKeys", "Style"),
    ("HashTransformValues", "Style"),
    ("HeredocArgumentClosingParenthesis", "Layout"),
    ("HeredocDelimiterCase", "Naming"),
    ("HeredocDelimiterNaming", "Naming"),
    ("HeredocIndentation", "Layout"),
    ("HeredocMethodCallPosition", "Lint"),
    ("IdenticalConditionalBranches", "Style"),
    ("IdentityComparison", "Lint"),
    ("IfInsideElse", "Style"),
    ("IfUnlessModifier", "Style"),
    ("IfUnlessModifierOfIfUnless", "Style"),
    ("IfWithBooleanLiteralBranches", "Style"),
    ("IfWithSemicolon", "Style"),
    ("ImplicitRuntimeError", "Style"),
    ("ImplicitStringConcatenation", "Lint"),
    ("InPatternThen", "Style"),
    ("InclusiveLanguage", "Naming"),
    ("IncompatibleIoSelectWithFiberScheduler", "Lint"),
    ("IndentationConsistency", "Layout"),
    ("IndentationStyle", "Layout"),
    ("IndentationWidth", "Layout"),
    ("IneffectiveAccessModifier", "Lint"),
    ("InfiniteLoop", "Style"),
    ("InheritException", "Lint"),
    ("InitialIndentation", "Layout"),
    ("InlineComment", "Style"),
    ("InsecureProtocolSource", "Bundler"),
    ("InterpolationCheck", "Lint"),
    ("InverseMethods", "Style"),
    ("InvertibleUnlessCondition", "Style"),
    ("IoMethods", "Security"),
    ("IpAddresses", "Style"),
    ("ItAssignment", "Style"),
    ("ItBlockParameter", "Style"),
    ("ItWithoutArgumentsInBlock", "Lint"),
    ("JSONLoad", "Security"),
    ("KeywordArgumentsMerging", "Style"),
    ("KeywordParametersOrder", "Style"),
    ("Lambda", "Style"),
    ("LambdaCall", "Style"),
    ("LambdaWithoutLiteralBlock", "Lint"),
    ("LeadingCommentSpace", "Layout"),
    ("LeadingEmptyLines", "Layout"),
    ("LineContinuationLeadingSpace", "Layout"),
    ("LineContinuationSpacing", "Layout"),
    ("LineEndConcatenation", "Style"),
    ("LineEndStringConcatenationIndentation", "Layout"),
    ("LineLength", "Layout"),
    ("LiteralAsCondition", "Lint"),
    ("LiteralAssignmentInCondition", "Lint"),
    ("LiteralInInterpolation", "Lint"),
    ("Loop", "Lint"),
    ("MagicCommentFormat", "Style"),
    ("MapCompactWithConditionalBlock", "Style"),
    ("MapIntoArray", "Style"),
    ("MapJoin", "Style"),
    ("MapToHash", "Style"),
    ("MapToSet", "Style"),
    ("MarshalLoad", "Security"),
    ("MemoizedInstanceVariableName", "Naming"),
    ("MethodCallWithArgsParentheses", "Style"),
    ("MethodCallWithoutArgsParentheses", "Style"),
    ("MethodCalledOnDoEndBlock", "Style"),
    ("MethodDefParentheses", "Style"),
    ("MethodLength", "Metrics"),
    ("MethodName", "Naming"),
    ("MethodParameterName", "Naming"),
    ("MinMax", "Style"),
    ("MinMaxComparison", "Style"),
    ("MissingCopEnableDirective", "Lint"),
    ("MissingElse", "Style"),
    ("MissingRespondToMissing", "Style"),
    ("MissingSuper", "Lint"),
    ("MixedCaseRange", "Lint"),
    ("MixedRegexpCaptureTypes", "Lint"),
    ("MixinGrouping", "Style"),
    ("MixinUsage", "Style"),
    ("ModuleFunction", "Style"),
    ("ModuleLength", "Metrics"),
    ("ModuleMemberExistenceCheck", "Style"),
    ("MultilineArrayBraceLayout", "Layout"),
    ("MultilineArrayLineBreaks", "Layout"),
    ("MultilineAssignmentLayout", "Layout"),
    ("MultilineBlockChain", "Style"),
    ("MultilineBlockLayout", "Layout"),
    ("MultilineHashBraceLayout", "Layout"),
    ("MultilineHashKeyLineBreaks", "Layout"),
    ("MultilineIfModifier", "Style"),
    ("MultilineIfThen", "Style"),
    ("MultilineInPatternThen", "Style"),
    ("MultilineMemoization", "Style"),
    ("MultilineMethodArgumentLineBreaks", "Layout"),
    ("MultilineMethodCallBraceLayout", "Layout"),
    ("MultilineMethodCallIndentation", "Layout"),
    ("MultilineMethodDefinitionBraceLayout", "Layout"),
    ("MultilineMethodParameterLineBreaks", "Layout"),
    ("MultilineMethodSignature", "Style"),
    ("MultilineOperationIndentation", "Layout"),
    ("MultilineTernaryOperator", "Style"),
    ("MultilineWhenThen", "Style"),
    ("MutableConstant", "Style"),
    ("NegatedIf", "Style"),
    ("NegatedIfElseCondition", "Style"),
    ("NegatedUnless", "Style"),
    ("NegatedWhile", "Style"),
    ("NegativeArrayIndex", "Style"),
    ("NestedFileDirname", "Style"),
    ("NestedMethodDefinition", "Lint"),
    ("NestedModifier", "Style"),
    ("NestedParenthesizedCalls", "Style"),
    ("NestedPercentLiteral", "Lint"),
    ("NestedTernaryOperator", "Style"),
    ("Next", "Style"),
    ("NextWithoutAccumulator", "Lint"),
    ("NilComparison", "Style"),
    ("NilLambda", "Style"),
    ("NoReturnInBeginEndBlocks", "Lint"),
    ("NonAtomicFileOperation", "Lint"),
    ("NonDeterministicRequireOrder", "Lint"),
    ("NonLocalExitFromIterator", "Lint"),
    ("NonNilCheck", "Style"),
    ("Not", "Style"),
    ("NumberConversion", "Lint"),
    ("NumberedParameterAssignment", "Lint"),
    ("NumberedParameters", "Style"),
    ("NumberedParametersLimit", "Style"),
    ("NumericLiteralPrefix", "Style"),
    ("NumericLiterals", "Style"),
    ("NumericOperationWithConstantResult", "Lint"),
    ("NumericPredicate", "Style"),
    ("ObjectThen", "Style"),
    ("OneClassPerFile", "Style"),
    ("OneLineConditional", "Style"),
    ("Open", "Security"),
    ("OpenStructUse", "Style"),
    ("OperatorMethodCall", "Style"),
    ("OptionHash", "Style"),
    ("OptionalArguments", "Style"),
    ("OptionalBooleanParameter", "Style"),
    ("OrAssignment", "Style"),
    ("OrAssignmentToConstant", "Lint"),
    ("OrderedDependencies", "Gemspec"),
    ("OrderedGems", "Bundler"),
    ("OrderedMagicComments", "Lint"),
    ("OutOfRangeRegexpRef", "Lint"),
    ("ParallelAssignment", "Style"),
    ("ParameterAlignment", "Layout"),
    ("ParameterLists", "Metrics"),
    ("ParenthesesAroundCondition", "Style"),
    ("ParenthesesAsGroupedExpression", "Lint"),
    ("PartitionInsteadOfDoubleSelect", "Style"),
    ("PerceivedComplexity", "Metrics"),
    ("PercentLiteralDelimiters", "Style"),
    ("PercentQLiterals", "Style"),
    ("PercentStringArray", "Lint"),
    ("PercentSymbolArray", "Lint"),
    ("PerlBackrefs", "Style"),
    ("PredicateMethod", "Naming"),
    ("PredicatePrefix", "Naming"),
    ("PredicateWithKind", "Style"),
    ("PreferredHashMethods", "Style"),
    ("Proc", "Style"),
    ("QuotedSymbols", "Style"),
    ("RaiseArgs", "Style"),
    ("RaiseException", "Lint"),
    ("RandOne", "Lint"),
    ("RandomWithOffset", "Style"),
    ("ReduceToHash", "Style"),
    ("RedundantArgument", "Style"),
    ("RedundantArrayConstructor", "Style"),
    ("RedundantArrayFlatten", "Style"),
    ("RedundantAssignment", "Style"),
    ("RedundantBegin", "Style"),
    ("RedundantCapitalW", "Style"),
    ("RedundantCondition", "Style"),
    ("RedundantConditional", "Style"),
    ("RedundantConstantBase", "Style"),
    ("RedundantCopDisableDirective", "Lint"),
    ("RedundantCopEnableDirective", "Lint"),
    ("RedundantCurrentDirectoryInPath", "Style"),
    ("RedundantDirGlobSort", "Lint"),
    ("RedundantDoubleSplatHashBraces", "Style"),
    ("RedundantEach", "Style"),
    ("RedundantException", "Style"),
    ("RedundantFetchBlock", "Style"),
    ("RedundantFileExtensionInRequire", "Style"),
    ("RedundantFilterChain", "Style"),
    ("RedundantFormat", "Style"),
    ("RedundantFreeze", "Style"),
    ("RedundantHeredocDelimiterQuotes", "Style"),
    ("RedundantInitialize", "Style"),
    ("RedundantInterpolation", "Style"),
    ("RedundantInterpolationUnfreeze", "Style"),
    ("RedundantLineBreak", "Layout"),
    ("RedundantLineContinuation", "Style"),
    ("RedundantMinMaxBy", "Style"),
    ("RedundantParentheses", "Style"),
    ("RedundantPercentQ", "Style"),
    ("RedundantRegexpArgument", "Style"),
    ("RedundantRegexpCharacterClass", "Style"),
    ("RedundantRegexpConstructor", "Style"),
    ("RedundantRegexpEscape", "Style"),
    ("RedundantRegexpQuantifiers", "Lint"),
    ("RedundantRequireStatement", "Lint"),
    ("RedundantReturn", "Style"),
    ("RedundantSafeNavigation", "Lint"),
    ("RedundantSelf", "Style"),
    ("RedundantSelfAssignment", "Style"),
    ("RedundantSelfAssignmentBranch", "Style"),
    ("RedundantSort", "Style"),
    ("RedundantSortBy", "Style"),
    ("RedundantSplatExpansion", "Lint"),
    ("RedundantStringCoercion", "Lint"),
    ("RedundantStringEscape", "Style"),
    ("RedundantStructKeywordInit", "Style"),
    ("RedundantTypeConversion", "Lint"),
    ("RedundantWithIndex", "Lint"),
    ("RedundantWithObject", "Lint"),
    ("RefinementImportMethods", "Lint"),
    ("RegexpAsCondition", "Lint"),
    ("RegexpLiteral", "Style"),
    ("RequireMFA", "Gemspec"),
    ("RequireOrder", "Style"),
    ("RequireParentheses", "Lint"),
    ("RequireRangeParentheses", "Lint"),
    ("RequireRelativeSelfPath", "Lint"),
    ("RequiredRubyVersion", "Gemspec"),
    ("RescueEnsureAlignment", "Layout"),
    ("RescueException", "Lint"),
    ("RescueModifier", "Style"),
    ("RescueStandardError", "Style"),
    ("RescueType", "Lint"),
    ("RescuedExceptionsVariableName", "Naming"),
    ("ReturnInVoidContext", "Lint"),
    ("ReturnNil", "Style"),
    ("ReturnNilInPredicateMethodDefinition", "Style"),
    ("ReverseFind", "Style"),
    ("RubyVersionGlobalsUsage", "Gemspec"),
    ("SafeNavigation", "Style"),
    ("SafeNavigationChain", "Lint"),
    ("SafeNavigationChainLength", "Style"),
    ("SafeNavigationConsistency", "Lint"),
    ("SafeNavigationWithEmpty", "Lint"),
    ("Sample", "Style"),
    ("ScriptPermission", "Lint"),
    ("SelectByKind", "Style"),
    ("SelectByRange", "Style"),
    ("SelectByRegexp", "Style"),
    ("Semicolon", "Style"),
    ("Send", "Style"),
    ("SendWithLiteralMethodName", "Style"),
    ("SendWithMixinArgument", "Lint"),
    ("ShadowedArgument", "Lint"),
    ("ShadowedException", "Lint"),
    ("ShadowingOuterLocalVariable", "Lint"),
    ("SharedMutableDefault", "Lint"),
    ("SignalException", "Style"),
    ("SingleArgumentDig", "Style"),
    ("SingleLineBlockChain", "Layout"),
    ("SingleLineBlockParams", "Style"),
    ("SingleLineDoEndBlock", "Style"),
    ("SingleLineMethods", "Style"),
    ("SlicingWithRange", "Style"),
    ("SoleNestedConditional", "Style"),
    ("SpaceAfterColon", "Layout"),
    ("SpaceAfterComma", "Layout"),
    ("SpaceAfterMethodName", "Layout"),
    ("SpaceAfterNot", "Layout"),
    ("SpaceAfterSemicolon", "Layout"),
    ("SpaceAroundBlockParameters", "Layout"),
    ("SpaceAroundEqualsInParameterDefault", "Layout"),
    ("SpaceAroundKeyword", "Layout"),
    ("SpaceAroundMethodCallOperator", "Layout"),
    ("SpaceAroundOperators", "Layout"),
    ("SpaceBeforeBlockBraces", "Layout"),
    ("SpaceBeforeBrackets", "Layout"),
    ("SpaceBeforeComma", "Layout"),
    ("SpaceBeforeComment", "Layout"),
    ("SpaceBeforeFirstArg", "Layout"),
    ("SpaceBeforeSemicolon", "Layout"),
    ("SpaceInLambdaLiteral", "Layout"),
    ("SpaceInsideArrayLiteralBrackets", "Layout"),
    ("SpaceInsideArrayPercentLiteral", "Layout"),
    ("SpaceInsideBlockBraces", "Layout"),
    ("SpaceInsideHashLiteralBraces", "Layout"),
    ("SpaceInsideParens", "Layout"),
    ("SpaceInsidePercentLiteralDelimiters", "Layout"),
    ("SpaceInsideRangeLiteral", "Layout"),
    ("SpaceInsideReferenceBrackets", "Layout"),
    ("SpaceInsideStringInterpolation", "Layout"),
    ("SpecialGlobalVars", "Style"),
    ("StabbyLambdaParentheses", "Style"),
    ("StaticClass", "Style"),
    ("StderrPuts", "Style"),
    ("StringChars", "Style"),
    ("StringConcatenation", "Style"),
    ("StringHashKeys", "Style"),
    ("StringLiterals", "Style"),
    ("StringLiteralsInInterpolation", "Style"),
    ("StringMethods", "Style"),
    ("Strip", "Style"),
    ("StructInheritance", "Style"),
    ("StructNewOverride", "Lint"),
    ("SuperArguments", "Style"),
    ("SuperWithArgsParentheses", "Style"),
    ("SuppressedException", "Lint"),
    ("SuppressedExceptionInNumberConversion", "Lint"),
    ("SwapValues", "Style"),
    ("SymbolArray", "Style"),
    ("SymbolConversion", "Lint"),
    ("SymbolLiteral", "Style"),
    ("SymbolProc", "Style"),
    ("Syntax", "Lint"),
    ("TallyMethod", "Style"),
    ("TernaryParentheses", "Style"),
    ("ToEnumArguments", "Lint"),
    ("ToJSON", "Lint"),
    ("TopLevelMethodDefinition", "Style"),
    ("TopLevelReturnWithArgument", "Lint"),
    ("TrailingBodyOnClass", "Style"),
    ("TrailingBodyOnMethodDefinition", "Style"),
    ("TrailingBodyOnModule", "Style"),
    ("TrailingCommaInArguments", "Style"),
    ("TrailingCommaInArrayLiteral", "Style"),
    ("TrailingCommaInAttributeDeclaration", "Lint"),
    ("TrailingCommaInBlockArgs", "Style"),
    ("TrailingCommaInHashLiteral", "Style"),
    ("TrailingEmptyLines", "Layout"),
    ("TrailingMethodEndStatement", "Style"),
    ("TrailingUnderscoreVariable", "Style"),
    ("TrailingWhitespace", "Layout"),
    ("TripleQuotes", "Lint"),
    ("TrivialAccessors", "Style"),
    ("UnderscorePrefixedVariableName", "Lint"),
    ("UnescapedBracketInRegexp", "Lint"),
    ("UnexpectedBlockArity", "Lint"),
    ("UnifiedInteger", "Lint"),
    ("UnlessElse", "Style"),
    ("UnlessLogicalOperators", "Style"),
    ("UnmodifiedReduceAccumulator", "Lint"),
    ("UnpackFirst", "Style"),
    ("UnreachableCode", "Lint"),
    ("UnreachableLoop", "Lint"),
    ("UnreachablePatternBranch", "Lint"),
    ("UnusedBlockArgument", "Lint"),
    ("UnusedMethodArgument", "Lint"),
    ("UriEscapeUnescape", "Lint"),
    ("UriRegexp", "Lint"),
    ("UselessAccessModifier", "Lint"),
    ("UselessAssignment", "Lint"),
    ("UselessConstantScoping", "Lint"),
    ("UselessDefaultValueArgument", "Lint"),
    ("UselessDefined", "Lint"),
    ("UselessElseWithoutRescue", "Lint"),
    ("UselessMethodDefinition", "Lint"),
    ("UselessNumericOperation", "Lint"),
    ("UselessOr", "Lint"),
    ("UselessRescue", "Lint"),
    ("UselessRuby2Keywords", "Lint"),
    ("UselessSetterCall", "Lint"),
    ("UselessTimes", "Lint"),
    ("VariableInterpolation", "Style"),
    ("VariableName", "Naming"),
    ("VariableNumber", "Naming"),
    ("Void", "Lint"),
    ("WhenThen", "Style"),
    ("WhileUntilDo", "Style"),
    ("WhileUntilModifier", "Style"),
    ("WordArray", "Style"),
    ("YAMLFileRead", "Style"),
    ("YAMLLoad", "Security"),
    ("YodaCondition", "Style"),
    ("YodaExpression", "Style"),
    ("ZeroLengthPredicate", "Style"),
];

/// rubocop's `RuboCop::ConfigObsoletion.legacy_cop_names` — every "renamed" /
/// "removed" / "split" / "extracted" cop rule's `old_name` from
/// `config/obsoletion.yml`, in FILE LOAD ORDER (matters: `DepartmentName#
/// qualified_legacy_cop_name` returns the FIRST array entry whose short name
/// matches, and a few short names recur under two old departments —
/// `PredicateName`, `SpaceAfterControlKeyword`, `SpaceBeforeModifierKeyword`).
/// `Performance/*`/`Rails/*` are literal entries from an "extracted" rule
/// (whole departments moved to gems) — their short-name segment is `*`,
/// which never matches an actual scanned token; kept verbatim for fidelity.
const LEGACY_COP_NAMES: &[&str] = &[
    "Layout/AlignArguments",
    "Layout/AlignArray",
    "Layout/AlignHash",
    "Layout/AlignParameters",
    "Layout/IndentArray",
    "Layout/IndentAssignment",
    "Layout/IndentFirstArgument",
    "Layout/IndentFirstArrayElement",
    "Layout/IndentFirstHashElement",
    "Layout/IndentFirstParameter",
    "Layout/IndentHash",
    "Layout/IndentHeredoc",
    "Layout/LeadingBlankLines",
    "Layout/Tab",
    "Layout/TrailingBlankLines",
    "Lint/BlockAlignment",
    "Lint/DefEndAlignment",
    "Lint/DuplicatedKey",
    "Lint/EndAlignment",
    "Lint/EndInMethod",
    "Lint/Eval",
    "Lint/HandleExceptions",
    "Lint/MultipleCompare",
    "Lint/StringConversionInInterpolation",
    "Lint/UnneededCopDisableDirective",
    "Lint/UnneededCopEnableDirective",
    "Lint/UnneededRequireStatement",
    "Lint/UnneededSplatExpansion",
    "Metrics/LineLength",
    "Naming/PredicateName",
    "Naming/UncommunicativeBlockParamName",
    "Naming/UncommunicativeMethodParamName",
    "Style/AccessorMethodName",
    "Style/AsciiIdentifiers",
    "Style/ClassAndModuleCamelCase",
    "Style/ConstantName",
    "Style/DeprecatedHashMethods",
    "Style/FileName",
    "Style/FlipFlop",
    "Style/MethodCallParentheses",
    "Style/MethodName",
    "Style/OpMethod",
    "Style/PredicateName",
    "Style/SingleSpaceBeforeFirstArg",
    "Style/UnneededCapitalW",
    "Style/UnneededCondition",
    "Style/UnneededInterpolation",
    "Style/UnneededPercentQ",
    "Style/UnneededSort",
    "Style/VariableName",
    "Style/VariableNumber",
    "Gemspec/DateAssignment",
    "Layout/SpaceAfterControlKeyword",
    "Layout/SpaceBeforeModifierKeyword",
    "Lint/InvalidCharacterLiteral",
    "Lint/RescueWithoutErrorClass",
    "Lint/SpaceBeforeFirstArg",
    "Lint/UselessComparison",
    "Style/BracesAroundHashParameters",
    "Style/MethodMissingSuper",
    "Style/SpaceAfterControlKeyword",
    "Style/SpaceBeforeModifierKeyword",
    "Style/TrailingComma",
    "Style/TrailingCommaInLiteral",
    "Style/MethodMissing",
    "Performance/*",
    "Rails/*",
];

fn dn_department_for(short_name: &str) -> Option<&'static str> {
    COP_DEPARTMENTS.iter().find(|(n, _)| *n == short_name).map(|(_, d)| *d)
}

fn dn_legacy_name_for(short_name: &str) -> Option<&'static str> {
    LEGACY_COP_NAMES.iter().find(|n| n.split('/').nth(1) == Some(short_name)).copied()
}

/// rubocop's `Registry.qualified_cop_name(name, nil, warn: false)` composed
/// with `DepartmentName#qualified_legacy_cop_name`: prefer a live cop's
/// department; fall back to the (old) department a renamed/removed/split/
/// extracted cop used to live under; else leave the name unqualified.
/// Upstream would pass `nil` to `corrector.replace` in that last case and
/// raise — not reachable from any example this fixture (or a well-formed
/// disable comment) produces, so falling back to a no-op replace instead of
/// upstream's crash is the sane choice here.
fn dn_qualify(short_name: &str) -> String {
    if let Some(dept) = dn_department_for(short_name) {
        format!("{dept}/{short_name}")
    } else if let Some(legacy) = dn_legacy_name_for(short_name) {
        legacy.to_string()
    } else {
        short_name.to_string()
    }
}

/// `DepartmentName#valid_content_token?`: a scanned token is fine as-is (not
/// a department-less cop name) when it's punctuation-only (a comma run, a
/// bare `/`-joined qualified name — `/` itself is non-word so this branch is
/// mostly subsumed by the punctuation check below, kept for fidelity), spells
/// `all`, or names an actual department.
fn dn_valid_content_token(token: &str) -> bool {
    static SLASH_OR_ALL: OnceLock<regex::Regex> = OnceLock::new();
    let re = SLASH_OR_ALL.get_or_init(|| regex::Regex::new(r"[A-Za-z]+/[A-Za-z]+|all").unwrap());
    token.chars().any(|c| !(c.is_ascii_alphanumeric() || c == '_'))
        || re.is_match(token)
        || DEPARTMENTS.contains(&token)
}

/// `DepartmentName#contain_unexpected_character_for_department_name?`: once
/// a scanned chunk holds a character outside `[A-Za-z/, ]` (a ` -- reason`
/// trailer, trailing prose, a `Style:Alias`-style typo, ...), the rest of the
/// comment is prose rather than more directive content, and scanning stops.
fn dn_has_unexpected_char(raw: &str) -> bool {
    raw.chars().any(|c| !(c.is_ascii_alphabetic() || c == '/' || c == ',' || c == ' '))
}

impl<'a> Cops<'a> {
    /// Migration/DepartmentName — ported from rubocop's `on_new_investigation`:
    /// every comment matching `DISABLE_COMMENT_FORMAT` (a `# rubocop:
    /// disable|enable|todo` directive, tolerating spaces around the `:`) has
    /// its tail scanned token-by-token with rubocop's own scanner
    /// (`/[^,]+|\W+/` — alternating "non-comma content" and "punctuation/
    /// whitespace run" chunks). Each content token that isn't already
    /// department-qualified, `all`, or a bare department name offends at its
    /// own start offset (comment start + running byte offset into the
    /// comment), autocorrecting to the registry-qualified (or legacy-
    /// obsoletion) name. Scanning a comment stops at the first chunk holding
    /// a character outside `[A-Za-z/, ]` — a ` -- reason` trailer or trailing
    /// prose comment.
    pub(crate) fn check_department_name(&mut self) {
        const COP: &str = "Migration/DepartmentName";
        if !self.on(COP) {
            return;
        }
        static DISABLE_RE: OnceLock<regex::Regex> = OnceLock::new();
        let disable_re = DISABLE_RE
            .get_or_init(|| regex::Regex::new(r"^(# *rubocop *: *((?:dis|en)able|todo) +)(.*)").unwrap());
        static SCAN_RE: OnceLock<regex::Regex> = OnceLock::new();
        let scan_re = SCAN_RE.get_or_init(|| regex::Regex::new(r"[^,]+|\W+").unwrap());

        for &(_, start, end) in self.comments {
            let text = String::from_utf8_lossy(&self.src[start..end]);
            let Some(caps) = disable_re.captures(&text) else { continue };
            let prefix_len = caps.get(1).unwrap().as_str().len();
            let tail = &text[prefix_len..];
            let mut offset = prefix_len;
            for m in scan_re.find_iter(tail) {
                let raw = m.as_str();
                let trimmed = raw.trim();
                if !dn_valid_content_token(trimmed) {
                    let cop_start = start + offset;
                    self.push(cop_start, COP, true, "Department name is missing.");
                    let qualified = dn_qualify(trimmed);
                    self.fixes.push((cop_start, cop_start + trimmed.len(), qualified.into_bytes()));
                }
                if dn_has_unexpected_char(raw) {
                    break;
                }
                offset += raw.len();
            }
        }
    }
}
