#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate src/plugin_config_gen.rs — the part of each plugin gem's
# `config/default.yml` that configures CORE rubocop: the `AllCops` keys it sets
# and its overrides of core cops. RuboCop merges a plugin's default.yml into
# `ConfigLoader.default_configuration`, so those entries apply to every run that
# names the gem on `plugins:`/`require:`, even though oxidecop implements none
# of the plugin's own cops.
#
#   ruby tools/gen_plugin_config.rb   # reads INSTALLED gems, rewrites the .rs
#
# Unlike tools/gen_schema.rb this reads the gems rather than vendor/ — the
# extracted slice is small and the generated file is checked in, so a build
# needs no gems. Rerun it with the plugin gems installed (any Rails app's
# Gemfile will do) to refresh: `BUNDLE_GEMFILE=… bundle exec ruby tools/…`.
require 'yaml'

ROOT = File.expand_path('..', __dir__)
OUT  = File.join(ROOT, 'src/plugin_config_gen.rs')

# Departments shipped by rubocop itself. Everything else in a plugin's
# default.yml configures its own cops, which oxidecop does not have.
CORE_DEPARTMENTS = %w[
  Bundler Gemspec Layout Lint Metrics Migration Naming Security Style
].freeze

# Plugin gems worth scanning: the ones a Rails/RSpec codebase loads.
GEMS = %w[
  rubocop-rails rubocop-rspec rubocop-rspec_rails rubocop-capybara
  rubocop-factory_bot rubocop-graphql rubocop-rake rubocop-performance
  rubocop-minitest rubocop-thread_safety rubocop-sequel rubocop-i18n
].freeze

# Cop metadata, plus `Enabled`: enablement belongs to the default layer that
# `AllCops: DisabledByDefault` flips wholesale, which this layer does not model
# — dropping it keeps a plugin from force-enabling a core cop the user disabled.
DROP_KEYS = %w[
  Description StyleGuide Reference References Enabled Severity
  VersionAdded VersionChanged VersionRemoved Safe SafeAutoCorrect AutoCorrect
].freeze

skipped = []

def rust_str(str)
  '"' + str.to_s.gsub('\\', '\\\\\\\\').gsub('"', '\\"') + '"'
end

# A list value in the flow form `Config`'s parser accepts. Items are
# single-quoted, so an item holding a quote has no encoding — the caller skips
# such an entry rather than emit something the parser would mangle.
def encode_list(items)
  return '[]' if items.empty?
  return nil if items.any? { |i| i.to_s.match?(/['"]/) }

  "[#{items.map { |i| "'#{i}'" }.join(', ')}]"
end

def encode(value)
  case value
  when Array then encode_list(value)
  when true, false, Integer, Float, String, Symbol then value.to_s
  end # nil (an unset key) and Hash (no flat form) fall through to nil
end

# `plugins: rubocop-rails` is the modern spelling; `require:` configs use one of
# the load paths. Mirrors `is_performance_plugin` in src/config.rs.
def plugin_names(gem_name)
  short = gem_name.delete_prefix('rubocop-')
  [gem_name, "rubocop/#{short}", "rubocop/cop/#{short}"]
end

rows = []
sources = []
no_core = []

GEMS.each do |gem_name|
  spec = begin
    Gem::Specification.find_by_name(gem_name)
  rescue Gem::MissingSpecError
    next
  end
  path = File.join(spec.gem_dir, 'config', 'default.yml')
  next unless File.exist?(path)

  yaml = YAML.safe_load(File.read(path), aliases: true, permitted_classes: [Regexp, Symbol])
  core = yaml.select do |key, _|
    key == 'AllCops' || CORE_DEPARTMENTS.include?(key.split('/').first)
  end
  if core.empty?
    no_core << "#{gem_name} #{spec.version}"
    next
  end
  sources << "#{gem_name} #{spec.version}"

  entries = core.flat_map do |section, conf|
    merged = Array((conf['inherit_mode'] || {})['merge'])
    conf.filter_map do |key, value|
      next if key == 'inherit_mode' || DROP_KEYS.include?(key)

      encoded = encode(value)
      if encoded.nil?
        skipped << "#{gem_name}: #{section} #{key} (#{value.class})"
        next
      end
      mode = merged.include?(key) ? 'Merge' : 'Override'
      "            (#{rust_str(section)}, #{rust_str(key)}, #{rust_str(encoded)}, " \
        "InheritMode::#{mode}),"
    end
  end

  rows << <<~ROW.chomp
        PluginConfig {
            names: &[#{plugin_names(gem_name).map { |n| rust_str(n) }.join(', ')}],
            entries: &[
    #{entries.join("\n")}
            ],
        },
  ROW
end

header = ["//! Sources (gem versions at extraction time): #{sources.join(', ')}."]
header << "//! Scanned, no core configuration: #{no_core.join(', ')}." unless no_core.empty?
unless skipped.empty?
  header << '//! Dropped — no flat representation in `Config`, so the core default stands:'
  header.concat(skipped.map { |s| "//!   #{s}" })
end

File.write(OUT, <<~RUST)
  //! GENERATED by tools/gen_plugin_config.rb from the plugin gems' own
  //! `config/default.yml` — DO NOT EDIT.
  //!
  //! One row per plugin gem: the `AllCops` keys it sets and its overrides of
  //! CORE cops, which RuboCop applies to every run that loads the gem. The
  //! gem's own cops are omitted — oxidecop implements none of them.
  //!
  #{header.join("\n")}
  use crate::config::{InheritMode, PluginConfig};

  pub const PLUGIN_CONFIGS: &[PluginConfig] = &[
  #{rows.join("\n")}
  ];
RUST
puts "wrote #{OUT}: #{rows.size} gems, #{skipped.size} dropped entries"
