#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate src/schema_gen.rs — the per-cop config SCHEMA — from rubocop's own
# config/default.yml, so parameter defaults / SupportedStyles / AllowedMethods
# are transcribed mechanically instead of hand-copied per cop.
#
#   ruby tools/gen_schema.rb          # reads vendor/, rewrites src/schema_gen.rs
#
# To bump the rubocop version: fetch the new default.yml into vendor/, update
# SRC below (and oracle/leaderboard.rb's REF), rerun, run the oracle.
require 'yaml'

ROOT = File.expand_path('..', __dir__)
SRC  = File.join(ROOT, 'vendor/rubocop-default-1.88.0.yml')
OUT  = File.join(ROOT, 'src/schema_gen.rs')

# Cop metadata keys that are not lintable parameters.
META = %w[
  Description StyleGuide Reference References Enabled Severity
  VersionAdded VersionChanged VersionRemoved
  Safe SafeAutoCorrect AutoCorrect
  Include Exclude
  SupportedStyles AllowedMethods
].freeze
# Exclude is not a lintable parameter, but default per-cop Excludes (e.g.
# Style/NumericPredicate skips spec/**/*) must ship with the schema.

def rust_str(s)
  '"' + s.to_s.gsub('\\', '\\\\\\\\').gsub('"', '\\"') + '"'
end

# A parameter default we can represent as a flat string (what Config::get
# hands back). Arrays/hashes other than the special-cased SupportedStyles /
# AllowedMethods are dropped — a cop that needs one grows engine support first.
def scalar(v)
  case v
  when true, false, Integer, Float then v.to_s
  when String, Symbol then v.to_s
  end
end

yaml = YAML.safe_load(File.read(SRC), aliases: true, permitted_classes: [Regexp, Symbol])
cops = yaml.select { |k, _| k.include?('/') }.sort_by { |k, _| k }

rows = cops.map do |cop, conf|
  conf ||= {}
  params = conf.filter_map do |k, v|
    next if META.include?(k)

    s = scalar(v)
    "(#{rust_str(k)}, #{rust_str(s)})" if s
  end
  styles = (conf['SupportedStyles'] || []).map { |s| rust_str(s) }
  allowed = (conf['AllowedMethods'] || []).map { |m| rust_str(m) }
  excludes = (conf['Exclude'] || []).map { |m| rust_str(m) }
  sg = conf['StyleGuide'] ? rust_str(conf['StyleGuide']) : 'e'
  sg = sg == 'e' ? 'None' : "Some(#{sg})"
  "    Schema { cop: #{rust_str(cop)}, params: &[#{params.join(', ')}], " \
    "styles: &[#{styles.join(', ')}], allowed_methods: &[#{allowed.join(', ')}], " \
    "excludes: &[#{excludes.join(', ')}], style_guide: #{sg} },"
end

File.write(OUT, <<~RUST)
  //! GENERATED by tools/gen_schema.rb from #{File.basename(SRC)} — DO NOT EDIT.
  //! One row per rubocop cop: parameter defaults (flat scalars), SupportedStyles,
  //! and default AllowedMethods, sorted by cop name (schema() binary-searches).
  use crate::config::Schema;

  pub const SCHEMA: &[Schema] = &[
  #{rows.join("\n")}
  ];
RUST
puts "wrote #{OUT}: #{rows.size} cops"
