//! GENERATED by tools/gen_plugin_config.rb from the plugin gems' own
//! `config/default.yml` — DO NOT EDIT.
//!
//! One row per plugin gem: the `AllCops` keys it sets and its overrides of
//! CORE cops, which RuboCop applies to every run that loads the gem. The
//! gem's own cops are omitted — oxidecop implements none of them.
//!
//! Sources (gem versions at extraction time): rubocop-rails 2.34.3, rubocop-rspec 3.9.0.
//! Scanned, no core configuration: rubocop-factory_bot 2.28.0, rubocop-graphql 1.6.0, rubocop-rake 0.7.1, rubocop-performance 1.26.1.
//! Dropped — no flat representation in `Config`, so the core default stands:
//!   rubocop-rails: AllCops TargetRailsVersion (NilClass)
//!   rubocop-rails: Style/InvertibleUnlessCondition InverseMethods (Hash)
use crate::config::{InheritMode, PluginConfig};

pub const PLUGIN_CONFIGS: &[PluginConfig] = &[
    PluginConfig {
        names: &["rubocop-rails", "rubocop/rails", "rubocop/cop/rails"],
        entries: &[
            ("AllCops", "Exclude", "['**/app/assets/**/*', 'bin/*', 'db/*schema.rb', 'log/**/*', 'public/**/*', 'storage/**/*']", InheritMode::Override),
            ("AllCops", "ActiveSupportExtensionsEnabled", "true", InheritMode::Override),
            ("AllCops", "MigratedSchemaVersion", "19700101000000", InheritMode::Override),
            ("Lint/NumberConversion", "AllowedMethods", "['ago', 'from_now', 'second', 'seconds', 'minute', 'minutes', 'hour', 'hours', 'day', 'days', 'week', 'weeks', 'fortnight', 'fortnights', 'in_milliseconds']", InheritMode::Override),
            ("Lint/NumberConversion", "AllowedPatterns", "[]", InheritMode::Override),
            ("Lint/RedundantSafeNavigation", "AllowedMethods", "['instance_of?', 'kind_of?', 'is_a?', 'eql?', 'respond_to?', 'equal?', 'presence', 'present?']", InheritMode::Override),
            ("Lint/SafeNavigationChain", "AllowedMethods", "['present?', 'blank?', 'presence', 'presence_in', 'try', 'try!', 'in?']", InheritMode::Override),
            ("Lint/UselessAccessModifier", "ContextCreatingMethods", "['class_methods', 'included', 'prepended', 'concern', 'concerning']", InheritMode::Merge),
            ("Lint/UselessMethodDefinition", "Exclude", "['**/app/controllers/**/*.rb', '**/app/mailers/**/*.rb']", InheritMode::Override),
            ("Style/AndOr", "EnforcedStyle", "conditionals", InheritMode::Override),
            ("Style/CollectionCompact", "AllowedReceivers", "['params']", InheritMode::Override),
            ("Style/FormatStringToken", "AllowedMethods", "['redirect']", InheritMode::Override),
            ("Style/SymbolProc", "AllowedMethods", "['define_method', 'mail', 'respond_to']", InheritMode::Override),
        ],
    },
    PluginConfig {
        names: &["rubocop-rspec", "rubocop/rspec", "rubocop/cop/rspec"],
        entries: &[
            ("Metrics/BlockLength", "Exclude", "['**/*_spec.rb', '**/spec/**/*']", InheritMode::Merge),
        ],
    },
];
